### ISSUE TITLE
Make repository private

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#1]
If this is just for testing, it might be best to make it private to avoid cluttering the organization view

**Comment by gmarupilla** [comment]
Yes, we can, but I don't have enough rights to make it a private repo.

**Comment by jonrkarr** [comment]
I think this should be public. The test suite will be an important resource for validating simulator images. We will want developers of simulator containers to use this test suite. In fact, we will want developers to contribute to this -- particularly archives that include models encoded in other languages such as CellML for which we don't yet have examples. For users, the test suite will serve as documentation of how we validated simulator images. For the community, this will also serve as a collection of example archives, which is somewhat lacking.

**Comment by bilalshaikh42** [comment]
Makes sense. I was not sure what the intentions were with it. Using it as a common place to store examples is a great idea.

**Comment by jonrkarr** [comment]
Akhil's intention might have been different. But I think its important for the test suite to be public.

**Comment by gmarupilla** [comment]
My idea is about saving available OMEX archives that every developer can use for all containers(new one's in the future) for testing locally, which is the same.

**Comment by jonrkarr** [comment]
This is what I started in `BioSimulations-utils`, along with code to use containers to execute the archives.

This repository now has the archives. The code to execute the archives is still in `BioSimulations-utils`.
