### ISSUE TITLE
Move results and vega figures into folders?

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#44]
Would it make sense to include the results and the vega figures into the folders that are zipped into the combine archive? Would make the repo a bit easier to navigate to keep everything in one folder. 
The figure is also something that we are planning to have included in the omex archive, and the results hdf file can be included as a "reference" result set for the test-suite/other uses

**Comment by jonrkarr** [comment]
I intend to move the figures inside the archives (and change the dispatch app to retrieve them from archives).

The expected and sample results could be moved as well:
- [x] Move files
- Update the links to these files
  - [x] `examples/README.md`
  - [x] `tests/test_examples.py`
  - [x] `biosimulators_test_suite/test_cases/published_project.py`

**Comment by jonrkarr** [comment]
Done in 4feec25656c4a469c8b0200b529c94f6f7ad205f.
