### ISSUE TITLE
Wrong warning when running the test suite.

### ISSUE THREAD

**Issue by danv61** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#54]
For published_project.SimulatorCanExecutePublishedProject:sbml-core/Caravagna-J-Theor-Biol-2010-tumor-suppressive-oscillations

Plots were not produced:
  BIOMD0000000912_sim.sedml/plot_1
Extra plots were produced:
  BIOMD0000000912_sim.sedml/Figure_1_bottom_left

The expected "plot_1" doesn't exist in the sedml file, the correct name is "Figure_1_bottom_left"

**Comment by jonrkarr** [comment]
Fixed in c8003d12ae3b9661cab5cb7e6626a66db4065df7. Deployed with 0.1.63.
