### ISSUE TITLE
Wrong warning when running the test suite.

### ISSUE THREAD

**Issue by danv61** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#55]
For published_project.SimulatorCanExecutePublishedProject:sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-Fehlberg

Plots were not produced:
  simulation.sedml/Figure_3a
Extra plots were produced:
  simulation_1.sedml/Figure_3a

The expected folder "simulation.sedml" is wrong, the correct folder name is "simulation_1.sedml"

**Comment by jonrkarr** [comment]
Fixed in c8003d12ae3b9661cab5cb7e6626a66db4065df7. Deployed with 0.1.63.
