### ISSUE TITLE
Update dev deployment of biosimulators along with prod when processing simulator submissions

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#60]
I have been keeping the two in sync manually by copying over the database every so often, but posting the results to dev as well would be an easier way to manage this

**Comment by jonrkarr** [comment]
I can do that. Easy to change.

**Comment by jonrkarr** [comment]
Done in 34c9d4b35f6dacc0a1527c9117cefbda93c6ff93. Will be deployed soon.
